name: 'Freedom'
description: 'Freedom auto renewal'
inputs:
  FREENOM_USERNAME:  # id of input
    description: 'FREENOM_USERNAME'
    required: true
  FREENOM_PASSWORD:  # id of input
    description: 'FREENOM_PASSWORD'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.FREENOM_USERNAME }}
    - ${{ inputs.FREENOM_PASSWORD }}
