name: Renewal freenom
on:
  schedule:
    - cron: '11 11 * * *'
  workflow_dispatch:
jobs:
  freenom:
    runs-on: ubuntu-latest
    steps:
    - uses: caojtop/freenom-action@main
      with:
        FREENOM_USERNAME: ${{ secrets.FREENOM_USERNAME }}
        FREENOM_PASSWORD: ${{ secrets.FREENOM_PASSWORD }}
        
